#   IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2023-1**<br>
**Profesor:** Rodrigo A. Carrasco <br>
---

# <h1><center>Actividad 05: Limpieza de datos</center></h1>

Esta actividad busca aplicar los conocimientos en transformación de datos para contestar algunas preguntas.

## Instrucciones

Esto Notebook contiene las instrucciones a realizar para la actividad. 

<b>Al finalizarla, deben subir el Notebook y los archivos generados a su repositorio personal, en una carpeta nueva llamada "Actividad 05". Asegúrese que ambas ayudantes tienen acceso a su repositorio para que puedan corregir. La actividad debe ser subida antes del final de la clase. Actualizaciones de su repositorio posteriores a esa fecha serán evaluadas con nota 1.0.</b>

## Actividad

Para esta actividad usaremos una base de datos obtenida de AirBnb que hemos bajado para usted. La base está dispobible en la carpeta `data` y el archivo se llama `listings.csv`.

## Rúbrica

- Si han logrado los puntos 1 y 2: 3.0
- Si han logrado hasta el punto 3: 4.0
- Si han logrado hasta el punto 5: 5.0
- Si han logrado todo: 7.0

In [2]:
# librerías necesarias para el ejercicio
import pandas as pd

## 1. Limpieza - datos relevantes

A continuación use las celdas para leer y transformar en un único DataFrame los datos que están en el archivo `listings.csv`.

Lea el archivo y liste sus columnas.

In [3]:
df = pd.read_csv("data/listings.csv")
df.columns.unique()

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

Para este trabajo, estaremos interesados sólo en las siguientes columnas:

['id',	'last_scraped',	'name',	'summary',	'description', 'city', 'state', 'country_code',	'latitude',	'longitude',	'room_type',	'accommodates',	'bathrooms',	'bedrooms',	'price',	'cleaning_fee', 'review_scores_rating',	'cancellation_policy']

Limpie los datos crudos para crear un DataFrame que sólo contenga estas columnas de información.

In [4]:
df = df[['id',	'last_scraped',	'name',	'summary',	'description',
        'city', 'state', 'country_code',	'latitude',	'longitude',
        'room_type',	'accommodates',	'bathrooms',	'bedrooms',	'price',	
        'cleaning_fee', 'review_scores_rating',	'cancellation_policy']]
df

id last_scraped                                 name  \
0         14576   2020-06-22               Dp Valen Castillo 1600   
1         30950   2020-06-22      Apartment Providencia, Santiago   
2         47936   2020-06-22                   My Flat in English   
3         49392   2020-06-22         Share my Flat in Providencia   
4         50466   2020-06-21  Great apartment at a great location   
...         ...          ...                                  ...   
15979  43860335   2020-06-21       Apartamento en alquiler diario   
15980  43861654   2020-06-21   Arriendo pieza individual amoblada   
15981  43861702   2020-06-26                      Casa compartida   
15982  43861718   2020-06-21                   Plaza de Armas 742   
15983  43862366   2020-06-21                    Plaza de Amas 742   

                                                 summary  \
0                                                    NaN   
1      Located in the heart of Providencia, near by r...   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
15979                                                NaN   
15980  Departamento antiguo en Barrio Bellas Artes, c...   
15981                                                NaN   
15982  Lindo departamento Ubicado en zona céntrica de...   
15983                                                NaN   

                                             description         city  \
0      Nice Flat in 11th floor in front of Mountains ...     Santiago   
1      Located in the heart of Providencia, near by r...     Santiago   
2      Nice and comfortable!  (Website hidden by Airbnb)     Santiago   
3      Departamento en el barrio Providencia. Complet...     Santiago   
4      Fully furnished LCD TV Wi-fi internet access A...     Santiago   
...                                                  ...          ...   
15979                                                NaN  Providencia   
15980  Departamento antiguo en Barrio Bellas Artes, c...     Santiago   
15981                                                NaN   Las Condes   
15982  Lindo departamento Ubicado en zona céntrica de...     Santiago   
15983                                                NaN     Santiago   

                      state country_code  latitude  longitude  \
0                     Chile           CL -33.46413  -70.64869   
1      Región Metropolitana           CL -33.43174  -70.61845   
2      Región Metropolitana           CL -33.44791  -70.63547   
3      Región Metropolitana           CL -33.43266  -70.60072   
4      Región Metropolitana           CL -33.43630  -70.65390   
...                     ...          ...       ...        ...   
15979  Región Metropolitana           CL -33.43376  -70.64090   
15980  Región Metropolitana           CL -33.43381  -70.64589   
15981  Región Metropolitana           CL -33.41197  -70.54748   
15982  Región Metropolitana           CL -33.43916  -70.65093   
15983  Región Metropolitana           CL -33.43896  -70.65077   

             room_type  accommodates  bathrooms  bedrooms       price  \
0      Entire home/apt             3        NaN       NaN  $81,730.00   
1      Entire home/apt             2        1.0       1.0  $19,615.00   
2         Private room             1        NaN       1.0  $44,952.00   
3         Private room             1        NaN       1.0  $44,952.00   
4      Entire home/apt             2        NaN       1.0  $69,471.00   
...                ...           ...        ...       ...         ...   
15979  Entire home/apt             3        1.0       1.0  $30,240.00   
15980     Private room             1        1.5       1.0  $11,442.00   
15981     Private room             4        1.0       2.0  $22,014.00   
15982  Entire home/apt             4        1.0       0.0  $34,327.00   
15

## 2. Limpieza - datos duplicados

Ahora asegure que en las filas de su DataFrame no existan datos duplicados. En caso de existir datos duplicados, dejar la primera aparición de los datos en el CSV como dato final. ¿Cuántos datos duplicados encontró?

In [5]:
df.duplicated().sum()

14

Respuesta: Se encontraron 14 datos repetidos.

## 3. Limpieza de texto y transformación

En la columna `price` está como texto el precio de cada una de las publicaciones. Corrija esos datos para contestar: ¿Cuál es el precio promedio de arriendos de AirBnb en esta base de datos?

In [9]:
df["price"] = df["price"].str.replace("$", "")
df["price"] = df["price"].str.replace(",", "")
df["price"] = df["price"].astype(float)

In [14]:
round(df["price"].mean())

91025

El precio promedio para las habitaciones es de 91025 pesos chilenos. 🤓👆

## 4. Variables categóricas

La variable `cancellation_policy` corresponde a una variable categórica. Identifique qué categorías tiene esta columna.

In [16]:

df["cancellation_policy"].unique()

array(['moderate', 'flexible', 'strict_14_with_grace_period',
       'super_strict_60', 'super_strict_30'], dtype=object)

'moderate', 'flexible', 'strict_14_with_grace_period', 'super_strict_60', 'super_strict_30' se encuentran en la columna

## 5. Cambios de categoría

Para nuetro análisis, sólo trabajaremos con las siguientes categorías: `moderate`,`flexible`,`strict`. Transforme la columna `cancellation_policy` para que se adapte a sólo estos tres posibles valores. Si cree que no es obvia la transformación, explique cómo decisió mapear cada categoría original a las categorías finales. Verifique que el DataFrame final sólo tiene esas categorías y conteste: ¿Cuántas publicaciones tenían una categoría `flexible`?

In [31]:
df_cp = df.loc[(df["cancellation_policy"] == "flexible") | 
       (df["cancellation_policy"] == "moderate") | 
       (df["cancellation_policy"] == "strict")]
df_cp

id last_scraped                                        name  \
0         14576   2020-06-22                      Dp Valen Castillo 1600   
1         30950   2020-06-22             Apartment Providencia, Santiago   
2         47936   2020-06-22                          My Flat in English   
3         49392   2020-06-22                Share my Flat in Providencia   
4         50466   2020-06-21         Great apartment at a great location   
...         ...          ...                                         ...   
15978  43858308   2020-06-22  Acogedor departamento 1D-1B en  Las Condes   
15979  43860335   2020-06-21              Apartamento en alquiler diario   
15980  43861654   2020-06-21          Arriendo pieza individual amoblada   
15981  43861702   2020-06-26                             Casa compartida   
15983  43862366   2020-06-21                           Plaza de Amas 742   

                                                 summary  \
0                                                    NaN   
1      Located in the heart of Providencia, near by r...   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
15978  Acogedor departamento 1D-1B con excelente ubic...   
15979                                                NaN   
15980  Departamento antiguo en Barrio Bellas Artes, c...   
15981                                                NaN   
15983                                                NaN   

                                             description         city  \
0      Nice Flat in 11th floor in front of Mountains ...     Santiago   
1      Located in the heart of Providencia, near by r...     Santiago   
2      Nice and comfortable!  (Website hidden by Airbnb)     Santiago   
3      Departamento en el barrio Providencia. Complet...     Santiago   
4      Fully furnished LCD TV Wi-fi internet access A...     Santiago   
...                                                  ...          ...   
15978  Acogedor departamento 1D-1B con excelente ubic...   Las Condes   
15979                                                NaN  Providencia   
15980  Departamento antiguo en Barrio Bellas Artes, c...     Santiago   
15981                                                NaN   Las Condes   
15983                                                NaN     Santiago   

                      state country_code  latitude  longitude  \
0                     Chile           CL -33.46413  -70.64869   
1      Región Metropolitana           CL -33.43174  -70.61845   
2      Región Metropolitana           CL -33.44791  -70.63547   
3      Región Metropolitana           CL -33.43266  -70.60072   
4      Región Metropolitana           CL -33.43630  -70.65390   
...                     ...          ...       ...        ...   
15978  Región Metropolitana           CL -33.41086  -70.58829   
15979  Región Metropolitana           CL -33.43376  -70.64090   
15980  Región Metropolitana           CL -33.43381  -70.64589   
15981  Región Metropolitana           CL -33.41197  -70.54748   
15983  Región Metropolitana           CL -33.43896  -70.65077   

             room_type  accommodates  bathrooms  bedrooms     price  \
0      Entire home/apt             3        NaN       NaN   81730.0   
1      Entire home/apt             2        1.0       1.0   19615.0   
2         Private room             1        NaN       1.0   44952.0   
3         Private room             1        NaN       1.0   44952.0   
4      Entire home/apt             2        NaN       1.0   69471.0   
...                ...           ...        ...       ...       ...   
15978  Entire home/apt             2        1.0       1.0  429900.0   
15979  Entire home/apt             3        1.0       1.0   30240.0   
15980     Private room             1        1.5       1.0   11442.0   
15981     P

In [34]:
df_cp[df_cp["cancellation_policy"] == "flexible"]["cancellation_policy"].count()

10249

Existen 10249 publicaciones con la categoría flexible. 🤓👆

## 6. Valores fuera de rango

Muchas veces las variables pueden tener valores furea de rango. Revise los datos de la columna `bedrooms`. ¿Encuentra que los valores están todos en un rango razonable? Si no lo están, revise el dato y verifique si hace sentido o no.

In [36]:
# Habitaciones con 0 habitaciones
df[df["bedrooms"].min() == df["bedrooms"]]

id last_scraped  \
439     2419113   2020-06-22   
506     2837601   2020-06-23   
511     2882770   2020-06-22   
567     3267803   2020-06-25   
573     3330669   2020-06-21   
...         ...          ...   
15918  43569457   2020-06-22   
15921  43579692   2020-06-22   
15926  43588797   2020-06-26   
15970  43834779   2020-06-21   
15982  43861718   2020-06-21   

                                                    name  \
439                         Departamento para 2 personas   
506                    el colorado, edificio monteblanco   
511                         Apto. Studio Santiago Centro   
567                            Departamento Estudio 1203   
573                  Downtown Santiago 2B/2B Modern Flat   
...                                                  ...   
15918                  HABITACION PRIVADA 1 baño privado   
15921                  habitación Privada 1 baño privado   
15926  Habitacion y baño privado Parque Araucano / ex...   
15970                                 Plaza de Armas 743   
15982                                 Plaza de Armas 742   

                                                 summary  \
439    Estudio amoblado , cama matrimonial , baño pri...   
506    Excelente recién remodelado, tipo loft con 2 a...   
511    Excelente ubicación del apartamento tipo Studi...   
567    HERMOSO APARTAMENTO ESTUDIO AMOBLADO Y EQUIPAD...   
573    Whether you are a couple, a family, a group of...   
...                                                  ...   
15918                                                NaN   
15921                                                NaN   
15926                                                NaN   
15970  Lindo departamento Ubicado en zona céntrica de...   
15982  Lindo departamento Ubicado en zona céntrica de...   

                                             description        city  \
439    Estudio amoblado , cama matrimonial , baño pri...    Santiago   
506    Excelente recién remodelado, tipo loft con 2 a...    Santiago   
511    Excelente ubicación del apartamento tipo Studi...    Santiago   
567    HERMOSO APARTAMENTO ESTUDIO AMOBLADO Y EQUIPAD...    Santiago   
573    Whether you are a couple, a family, a group of...    Santiago   
...                                                  ...         ...   
15918                                                NaN    Santiago   
15921                                                NaN    Santiago   
15926                                                NaN  Las Condes   
15970  Lindo departamento Ubicado en zona céntrica de...    Santiago   
15982  Lindo departamento Ubicado en zona céntrica de...    Santiago   

                                           state country_code  latitude  \
439    Región Metropolitana de Santiago de Chile           CL -33.43967   
506                         Región Metropolitana           CL -33.34531   
511                         Región Metropolitana           CL -33.44078   
567                         Región Metropolitana           CL -33.42568   
573                 Santiago Metropolitan Region           CL -33.45110   
...                                          ...          ...       ...   
15918                       Región Metropolitana           CL -33.43969   
15921                       Región Metropolitana           CL -33.43889   
15926                       Región Metropolitana           CL -33.40461   
15970                       Región Metropolitana           CL -33.43899   
15982                       Región Metropolitana           CL -33.43916   

       longitude        room_type  accommodates  bathrooms  bedrooms  \
439    -70.65694  Entire home/apt             2        1.0       0.0   
506    -70.29464  Entire home/apt             4        1.0       0.0   
511    -70.65774  Entire home/apt             2        1.0       0.0   
567    -70.61553  Entire home/apt             2        1.0       0.0   
573    -70.65566  Entire home/apt             4        0.0  

El DF anterior representa los valores en donde las habitaciones son 0, y notemos que a simple vista no sentido, ya que un arriendo al menos deberia tener 1 habitacion. Sin embargo, al analizar "Entire home/apt", notemos que se pueden tratar de estudios u oficinas que no tienen habitaciones, por lo que no es un dato erroneo.

In [37]:
df[df["bedrooms"].max() == df["bedrooms"]]

id last_scraped                                          name  \
15878  43389813   2020-06-22  Hotel Brasilia, La capital del barrio Brasil   

                                                 summary  \
15878  El Hotel Brasilia se encuentra a 5 km del Pati...   

                                             description      city  \
15878  El Hotel Brasilia se encuentra a 5 km del Pati...  Santiago   

                      state country_code  latitude  longitude     room_type  \
15878  Región Metropolitana           CL -33.43831  -70.66847  Private room   

       accommodates  bathrooms  bedrooms    price cleaning_fee  \
15878             2       50.0      50.0  67836.0          NaN   

       review_scores_rating cancellation_policy  
15878                   NaN            flexible

El DF anterior representa el caso donde existen 50 habitaciones, a simple vista notamos que no tiene sentido, pero al analizar el DF, notamos que se trata de un hotel, por lo que el dato es correcto.

In [39]:
df["bedrooms"].describe()

count    15951.000000
mean         1.371325
std          1.107049
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         50.000000
Name: bedrooms, dtype: float64

Ademas si analizamos los datos de las habitaciones notemos que los valores estan principalmente entre 1 y 2, por lo que los datos son correctos. Sin embargo, existen los casos extremos donde se arriendan 0 o 50 habitaciones, pero como se menciono anteriormente, estos datos son correctos o tienen sentido al analizar el DF.